[pytest]
testpaths = src/steps
python_files = test_*.py
addopts = -v --tb=short --alluredir=reports/allure-results
markers =
    LoginPage: Scenarios for the login page
    InvalidCredentials: Scenarios with invalid credentials
    Sanity: Sanity check test cases
    API: API test cases
    APILogin: API login and transaction scenarios
    Smoke: Smoke test cases
    Regression: Regression test cases
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
