Project=ICICI Pru - Anti-Money Laundering
Environment=SIT
Devices=chromium, firefox
Browsers=Chromium, Firefox
Platform=win32
Framework=Playwright-BDD (Python)
Version=1.0.0
Python=v3.12.10
BuildNumber=
CommitHash=
Description=BDD tags: LoginPage, InvalidCredentials, Sanity
Browsers Tested=chromium, firefox
Executions=11
Failed On=None
